### ISSUE TITLE
Super weird Angular

### ISSUE THREAD

**Issue by sdegennaro** [sdegennaro/Project4_KiteForecast#2]
I have a scope variable that I'd like to change and display when a certain function runs. Right now, the text is only rendering when I type something in a text box that's totally unrelated. 👻 👻 👻

**Comment by ajhofferber** [comment]
I'm closing this because I know you figured it out! 👍 👍 👍 👍 👍 👍

**Comment by ajhofferber** [comment]
jk. not closing it. can't close it. 😛
